---
language: perl
sudo: required
services:
  - docker

before_script:
  - make -f ci/Makefile

script:
  - make -f ci/Makefile test

after_script:
  - make -f ci/Makefile clean

env:
  matrix:
    - MESOS_VERSION=0.20.1-1.0.ubuntu1404   PROTOBUF_VERSION=2.5.0 PERL_VERSION=5.10.1
    - MESOS_VERSION=0.20.1-1.0.ubuntu1404   PROTOBUF_VERSION=2.5.0 PERL_VERSION=5.10.1-threaded
    - MESOS_VERSION=0.20.1-1.0.ubuntu1404   PROTOBUF_VERSION=2.5.0 PERL_VERSION=5.24.0
    - MESOS_VERSION=0.20.1-1.0.ubuntu1404   PROTOBUF_VERSION=2.5.0 PERL_VERSION=5.24.0-threaded
    - MESOS_VERSION=0.20.1-1.0.ubuntu1404   PROTOBUF_VERSION=2.6.0 PERL_VERSION=5.10.1
    - MESOS_VERSION=0.20.1-1.0.ubuntu1404   PROTOBUF_VERSION=2.6.0 PERL_VERSION=5.10.1-threaded
    - MESOS_VERSION=0.20.1-1.0.ubuntu1404   PROTOBUF_VERSION=2.6.0 PERL_VERSION=5.24.0
    - MESOS_VERSION=0.20.1-1.0.ubuntu1404   PROTOBUF_VERSION=2.6.0 PERL_VERSION=5.24.0-threaded
    - MESOS_VERSION=1.0.1-2.0.93.ubuntu1404 PROTOBUF_VERSION=2.5.0 PERL_VERSION=5.10.1
    - MESOS_VERSION=1.0.1-2.0.93.ubuntu1404 PROTOBUF_VERSION=2.5.0 PERL_VERSION=5.10.1-threaded
    - MESOS_VERSION=1.0.1-2.0.93.ubuntu1404 PROTOBUF_VERSION=2.5.0 PERL_VERSION=5.24.0
    - MESOS_VERSION=1.0.1-2.0.93.ubuntu1404 PROTOBUF_VERSION=2.5.0 PERL_VERSION=5.24.0-threaded
    - MESOS_VERSION=1.0.1-2.0.93.ubuntu1404 PROTOBUF_VERSION=2.6.0 PERL_VERSION=5.10.1
    - MESOS_VERSION=1.0.1-2.0.93.ubuntu1404 PROTOBUF_VERSION=2.6.0 PERL_VERSION=5.10.1-threaded
    - MESOS_VERSION=1.0.1-2.0.93.ubuntu1404 PROTOBUF_VERSION=2.6.0 PERL_VERSION=5.24.0
    - MESOS_VERSION=1.0.1-2.0.93.ubuntu1404 PROTOBUF_VERSION=2.6.0 PERL_VERSION=5.24.0-threaded

