language: perl
perl:
  #- "blead-thr"
  #- "blead"
  #- "5.24-thr"
  - "5.24"
  #- "5.22-thr"
  - "5.22"
  #- "5.20-thr"
  - "5.20"
  #- "5.18-thr"
  - "5.18"
  #- "5.16-thr"
  - "5.16"
  #- "5.14-thr"
  - "5.14"
  #- "5.12-thr"
  - "5.12"
  #- "5.10-thr"
  - "5.10"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install wget tar make g++ git
  - .travis/install-mesos.sh
  - .travis/install-protobuf.sh

install:
  - cpanm --with-configure --with-develop --installdeps --notest .
