---
code:
  build: ..
  dockerfile: ci/Dockerfile
  command: /bin/true
  environment:
    CI: 'true'
    MESOS_TEST_MASTER: zk://zookeeper:2181/mesos
    USER: ci-user
  links:
    - mesos-master
    - mesos-slave
    - zookeeper

mesos-master:
  build: ..
  dockerfile: ci/Dockerfile
  command: mesos-master --registry=in_memory
  environment:
    MESOS_PORT: 5050
    MESOS_ZK: zk://zookeeper:2181/mesos
    MESOS_QUORUM: 1
  privileged: true
  ports:
    - "5050"
  links:
    - zookeeper

mesos-slave:
  build: ..
  dockerfile: ci/Dockerfile
  command: mesos-slave
  environment:
    MESOS_PORT: 5051
    MESOS_MASTER: zk://zookeeper:2181/mesos
    MESOS_SWITCH_USER: 0
  privileged: true
  ports:
    - "5051"
  links:
    - zookeeper

zookeeper:
  image: jplock/zookeeper:3.4.8
  ports:
    - "2181"

